package com.github.bkmbigo.solitaire.presentation.ui.game.card.solitaire.layouts.utils

enum class SolitaireLayoutId {
    EMPTY_DECK,
    DECK_OVERLAY,
    DECK_CARD,

    EMPTY_FOUNDATION_SPADE,
    EMPTY_FOUNDATION_CLOVER,
    EMPTY_FOUNDATION_HEARTS,
    EMPTY_FOUNDATION_DIAMOND,

    FOUNDATION_SPADE,
    FOUNDATION_CLOVER,
    FOUNDATION_HEARTS,
    FOUNDATION_DIAMOND,

    FIRST_TABLE_STACK,
    SECOND_TABLE_STACK,
    THIRD_TABLE_STACK,
    FOURTH_TABLE_STACK,
    FIFTH_TABLE_STACK,
    SIXTH_TABLE_STACK,
    SEVENTH_TABLE_STACK
}
