on:
  release:
    types: [created]
name: Release Artifacts
jobs:
    release-ide:
      name: Release IDE Plugin
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - uses: actions/setup-java@v1
          with:
            java-version: '17'
            java-package: jdk
  
        - name: Validate gradle wrapper
          uses: gradle/wrapper-validation-action@v1

        - name: Build IDE Plugin
          run: ./gradlew :ide-plugins:intellij:buildPlugin

        - name: Upload IDE Plugin
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            files: |
              ide-plugins/intellij/build/releases/Solitaire Compose.zip
